### ISSUE TITLE
Memory Chat Shows incorrect mb

### ISSUE THREAD

**Issue by indra452** [bainternet/Memchaced-Dashboard#7]
Hi,
Thank you for sharing the Memcached Dashboard. You did a wonderful job.

In memory chart , Total memory is showing 2MB. But the actual MB is 2048. I mean 2 GB.

Number of bytes this server is allowed to use for storage is shown correctly.

**Comment by bainternet** [comment]
Not sure what you mean?

**Comment by indra452** [comment]
I have allocated 2048MB for memcache. But the chart is showing 2MB as total memory

**Comment by bainternet** [comment]
can you add a screenshot?

**Comment by indra452** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5727002/10675778/bee5a572-791f-11e5-8301-b9259c466079.png)

**Comment by indra452** [comment]
Added screenshot Pls check it
