### ISSUE TITLE
How to use Set Stored Keys area

### ISSUE THREAD

**Issue by jaybenkovich** [bainternet/Memchaced-Dashboard#8]
Can you give an example of how to set stored keys, if at all?  Your pictures shows information in there and I am wondering if we need to put in information to monitor the proper keys?
Thanks
Jay

**Comment by bainternet** [comment]
you can set the keys to what ever you'd like, the keys in the image are actually set by [Memcached Object Cache WordPress plugin](https://wordpress.org/plugins/memcached/).
